"""Subclass of MainFrame, which is generated by wxFormBuilder."""

import wx
from AspBBFinderMainFrame import AspBBFinderMainFrame
from Finder import Finder

# Override MainFrame
class AspBBFinderMainFrameChild( AspBBFinderMainFrame ):
	def __init__( self, parent ):
		AspBBFinderMainFrame.__init__( self, parent )
		self.finder=Finder()
	# Handlers for MainFrame events.
	def AspBtn1OnButtonClick( self, event ):
		# TODO: Implement AspBtn1OnButtonClick
		res = self.finder.AspFinder()
		self.AspMsg2.SetLabel(res)
		

	def BBBtn1OnButtonClick( self, event ):
		# TODO: Implement BBBtn1OnButtonClick
		try:
			res = self.finder.BBFinder()
		except TypeError:           
			res = 'クリップボードに画像がありません'
			self.BBMsg2.SetLabel(res)
		except Exception as e:
			res = 'Error: ' + str(e) +'\n暗いシーンでないか確認してください'
			self.BBMsg2.SetLabel(res)
		self.BBMsg2.SetLabel(res)
		
