"""Subclass of MainFrame, which is generated by wxFormBuilder."""

import wx
import AspFinderBB

# Implementing MainFrame
class AspBBFinderMainFrame( AspFinderBB.MainFrame ):
	def __init__( self, parent ):
		AspFinderBB.MainFrame.__init__( self, parent )

	# Handlers for MainFrame events.
	def AspBtn1OnButtonClick( self, event ):
		# TODO: Implement AspBtn1OnButtonClick
		pass

	def BBBtn1OnButtonClick( self, event ):
		# TODO: Implement BBBtn1OnButtonClick
		pass


