"""Subclass of Main, which is generated by wxFormBuilder."""

import wx
import MyApp
from MyProject1Main import MyProject1Main
from PIL import ImageGrab, Image

def get_aspect(m, n):
    w = m
    h = n
    while n > 0:
        tmp = n
        n = m % n
        m = tmp

    return w//m, h//m

class MyProject1MainChild( MyProject1Main ):
	def __init__( self, parent ):
		MyProject1Main.__init__( self, parent )

	# Handlers for MyFrame1 events.
	def m_button1OnButtonClick( self, event ):
		# TODO: Implement m_button1OnButtonClick

		im = ImageGrab.grabclipboard()
		try:
			width, height = im.size
			width = round(width, -1)
			height = round(height, -1)
			
			asp = get_aspect(width,height)
			msg = "アスペクト比は"+str(asp[0])+':'+str(asp[1])
			self.m_staticText2.SetLabel(msg)
		except AttributeError:
			msg = 'クリップボードに画像がありません。'
			self.m_staticText2.SetLabel(msg)
			

		