"""Subclass of Main, which is generated by wxFormBuilder."""

import wx
import MyApp

# Implementing Main
class MyProject1Main( MyApp.Main ):
	def __init__( self, parent ):
		MyApp.Main.__init__( self, parent )

	# Handlers for Main events.
	def m_button1OnButtonClick( self, event ):
		# TODO: Implement m_button1OnButtonClick
		pass


